name: CI
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt || true
      - name: Unicode path policy
        run: python tools/map_aliases.py --check
      - name: Canon validator
        run: python tools/validate_journal_enhanced.py || true
      - name: Drift/Echo validator
        run: python tools/ci_checks.py || true
