name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build dist
        run: python tools/build_dist.py --aliases aliases.json --out dist/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iskra-dist
          path: dist/
