name: CI
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install & Lint
        run: |
          python -m pip install --upgrade pip
          if [ -f iskra_audit_tool/requirements.txt ]; then pip install -r iskra_audit_tool/requirements.txt; fi
          if [ -d tests ]; then python -m pytest -q || true; fi
